version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run: 
        name: compile code
        command: |
          mkdir output
          echo "hello world" > output/message.txt
      - persist_to_workspace:
        root: output
        paths:
          - message.txt
          
  test:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run: echo "hello world"
